<a href="https://colab.research.google.com/github/Rahuld-242/Rahul_dcoding/blob/main/Text_Generation_With_Python_and_Keras_checkpoint.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Part One: The Data

* Import Main Libraries
* Importing Text
* Understanding Characters

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
%tensorflow_version 2.x
import tensorflow as tf

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


In [3]:
path_to_file="shakespeare.txt"

In [4]:
text=open(path_to_file,'r').read()

In [5]:
#print(text[140500:141800])

In [7]:
vocab=sorted(set(text))
vocab

['\n',
 ' ',
 '!',
 '"',
 '&',
 "'",
 '(',
 ')',
 ',',
 '-',
 '.',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 ':',
 ';',
 '<',
 '>',
 '?',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 '[',
 ']',
 '_',
 '`',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 '|',
 '}']

In [9]:
len(vocab)

84

## Part Two: Text Processing

* Vectorize the text
* Create encoding dictionary

In [10]:
#for pair in enumerate(vocab):
#    print(pair)

In [11]:
char_to_ind={char: ind for ind,char in enumerate(vocab)}

In [12]:
char_to_ind['H']

33

In [13]:
ind_to_char=np.array(vocab)

In [14]:
ind_to_char[33]

'H'

In [15]:
encoded_text=np.array([char_to_ind[c] for c in text])

In [16]:
encoded_text.shape

(5445609,)

In [17]:
sample=text[:500]

In [18]:
sample

"\n                     1\n  From fairest creatures we desire increase,\n  That thereby beauty's rose might never die,\n  But as the riper should by time decease,\n  His tender heir might bear his memory:\n  But thou contracted to thine own bright eyes,\n  Feed'st thy light's flame with self-substantial fuel,\n  Making a famine where abundance lies,\n  Thy self thy foe, to thy sweet self too cruel:\n  Thou that art now the world's fresh ornament,\n  And only herald to the gaudy spring,\n  Within thine own bu"

In [19]:
encoded_text[:500]

array([ 0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1, 12,  0,  1,  1, 31, 73, 70, 68,  1, 61, 56, 64,
       73, 60, 74, 75,  1, 58, 73, 60, 56, 75, 76, 73, 60, 74,  1, 78, 60,
        1, 59, 60, 74, 64, 73, 60,  1, 64, 69, 58, 73, 60, 56, 74, 60,  8,
        0,  1,  1, 45, 63, 56, 75,  1, 75, 63, 60, 73, 60, 57, 80,  1, 57,
       60, 56, 76, 75, 80,  5, 74,  1, 73, 70, 74, 60,  1, 68, 64, 62, 63,
       75,  1, 69, 60, 77, 60, 73,  1, 59, 64, 60,  8,  0,  1,  1, 27, 76,
       75,  1, 56, 74,  1, 75, 63, 60,  1, 73, 64, 71, 60, 73,  1, 74, 63,
       70, 76, 67, 59,  1, 57, 80,  1, 75, 64, 68, 60,  1, 59, 60, 58, 60,
       56, 74, 60,  8,  0,  1,  1, 33, 64, 74,  1, 75, 60, 69, 59, 60, 73,
        1, 63, 60, 64, 73,  1, 68, 64, 62, 63, 75,  1, 57, 60, 56, 73,  1,
       63, 64, 74,  1, 68, 60, 68, 70, 73, 80, 21,  0,  1,  1, 27, 76, 75,
        1, 75, 63, 70, 76,  1, 58, 70, 69, 75, 73, 56, 58, 75, 60, 59,  1,
       75, 70,  1, 75, 63

## Part Three: Creating Batches

* Understand text sequences
* Use Tensorflow datasets to generate batches
* Shuffle batches

In [20]:
print(text[:500])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bu


In [21]:
line="From fairest creatures we desire increase"

In [22]:
len(line)

41

In [23]:
lines="""
 From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,

"""

In [24]:
len(lines)

135

In [25]:
seq_len=120

In [26]:
total_num_seq=len(text)//(seq_len+1)

In [27]:
total_num_seq

45005

In [28]:
char_dataset=tf.data.Dataset.from_tensor_slices(encoded_text)

In [29]:
type(char_dataset)

tensorflow.python.data.ops.from_tensor_slices_op._TensorSliceDataset

In [30]:
#for item in char_dataset.take(500):
#    print(ind_to_char[item.numpy()])

In [31]:
sequences=char_dataset.batch(seq_len+1,drop_remainder=True)

In [32]:
def create_seq_targets(seq):
    input_txt=seq[:-1]
    target_txt=seq[1:]
    return input_txt, target_txt

In [33]:
dataset=sequences.map(create_seq_targets)

In [34]:
for input_txt, target_txt in dataset.take(1):
    print(input_txt.numpy())
    print("".join(ind_to_char[input_txt.numpy()]))
    print("\n")
    print(target_txt.numpy())
    print("".join(ind_to_char[target_txt.numpy()]))

[ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0
  1  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74
  1 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45
 63 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74
 60  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75]

                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But


[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0  1
  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74  1
 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45 63
 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74 60
  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75  1]
                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But 


In [35]:
batch_size=128

In [36]:
buffer_size=10000
dataset=dataset.shuffle(buffer_size).batch(batch_size,drop_remainder=True)

In [37]:
dataset

<_BatchDataset element_spec=(TensorSpec(shape=(128, 120), dtype=tf.int64, name=None), TensorSpec(shape=(128, 120), dtype=tf.int64, name=None))>

## Part Four: Creating the Model

* Set up loss function
* Create Model
  * Embedding
  * GRU
  * Dense

In [38]:
vocab_size=len(vocab)

In [39]:
embed_dim=64

In [40]:
rnn_neurons=1026

In [41]:
from tensorflow.keras.losses import sparse_categorical_crossentropy


In [42]:
help(sparse_categorical_crossentropy)

Help on function sparse_categorical_crossentropy in module keras.losses:

sparse_categorical_crossentropy(y_true, y_pred, from_logits=False, axis=-1, ignore_class=None)
    Computes the sparse categorical crossentropy loss.
    
    Standalone usage:
    
    >>> y_true = [1, 2]
    >>> y_pred = [[0.05, 0.95, 0], [0.1, 0.8, 0.1]]
    >>> loss = tf.keras.losses.sparse_categorical_crossentropy(y_true, y_pred)
    >>> assert loss.shape == (2,)
    >>> loss.numpy()
    array([0.0513, 2.303], dtype=float32)
    
    >>> y_true = [[[ 0,  2],
    ...            [-1, -1]],
    ...           [[ 0,  2],
    ...            [-1, -1]]]
    >>> y_pred = [[[[1.0, 0.0, 0.0], [0.0, 0.0, 1.0]],
    ...             [[0.2, 0.5, 0.3], [0.0, 1.0, 0.0]]],
    ...           [[[1.0, 0.0, 0.0], [0.0, 0.5, 0.5]],
    ...            [[0.2, 0.5, 0.3], [0.0, 1.0, 0.0]]]]
    >>> loss = tf.keras.losses.sparse_categorical_crossentropy(
    ...   y_true, y_pred, ignore_class=-1)
    >>> loss.numpy()
    array([[[2.384

In [43]:
#default from_logits=False
#Need to create function to change from_logits to true

def sparse_cat_loss(y_true, y_pred):
    return sparse_categorical_crossentropy(y_true, y_pred, from_logits=True)

In [44]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, GRU, Dense

In [45]:
def create_model(vocab_size, embed_dim, rnn_neurons, batch_size):
    model=Sequential()
    model.add(Embedding(vocab_size,embed_dim,batch_input_shape=[batch_size,None]))
    model.add(GRU(rnn_neurons, return_sequences=True, stateful=True, recurrent_initializer='glorot_uniform'))
    model.add(Dense(vocab_size))

    model.compile('adam',loss=sparse_cat_loss)

    return model


In [46]:
model=create_model(vocab_size=vocab_size, embed_dim=embed_dim, rnn_neurons=rnn_neurons, batch_size=batch_size)

In [47]:
model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (128, None, 64)           5376      
                                                                 
 gru (GRU)                   (128, None, 1026)         3361176   
                                                                 
 dense (Dense)               (128, None, 84)           86268     
                                                                 
Total params: 3,452,820
Trainable params: 3,452,820
Non-trainable params: 0
_________________________________________________________________


## Part Five: Training the Model



In [50]:
#This is to test if the model is running correctly
for input_example_batch, target_example_batch in dataset.take(1):

  example_batch_predictions=model(input_example_batch)

In [52]:
example_batch_predictions[0]

<tf.Tensor: shape=(120, 84), dtype=float32, numpy=
array([[ 0.00299996,  0.0021466 ,  0.00267193, ...,  0.00899008,
         0.00821382, -0.00268497],
       [ 0.00333127, -0.00269304, -0.00878132, ...,  0.00670156,
         0.00305085,  0.00102584],
       [-0.00235063,  0.00098842,  0.00018135, ...,  0.00839527,
         0.00288711,  0.00708124],
       ...,
       [ 0.00342015,  0.00124391,  0.00324163, ..., -0.00253288,
         0.00221732,  0.00253737],
       [ 0.00494753,  0.00506862,  0.00203646, ..., -0.00064197,
         0.00310355, -0.00424707],
       [ 0.00758349,  0.00309199,  0.00543094, ..., -0.00076241,
        -0.00216081,  0.00024673]], dtype=float32)>

In [54]:
sampled_indices=tf.random.categorical(example_batch_predictions[0],num_samples=1)

In [55]:
sampled_indices=tf.squeeze(sampled_indices,axis=-1).numpy()

In [56]:
ind_to_char[sampled_indices]

array(['|', 'K', 'J', '_', ')', 'K', ' ', 'i', '8', 'X', 'n', 'd', 'p',
       '-', 'c', 'h', 'R', 'b', '"', 'M', 'F', 'q', '\n', '&', '4', '<',
       '1', 'G', 'H', 'q', 'c', ')', '|', 'v', '5', 'A', '(', '4', '!',
       'z', 'b', '-', 'D', 'q', '`', 'B', 'd', '8', '[', 'a', 'e', '&',
       '!', '-', '\n', 'F', ':', 'J', 'U', 'g', 'V', "'", '5', '|', 'k',
       'l', 'i', '_', '7', 'C', 'U', '"', 'p', 'w', 'J', 'G', '}', 'B',
       'N', 'n', 'k', 'q', ']', 'P', 'A', '!', 'r', '4', '"', 'n', '[',
       'F', '-', 'z', '0', 'o', 'h', 'O', 'r', 'K', 'q', 'T', 'O', 'k',
       '\n', 'x', '"', 'P', ' ', 'A', '?', '5', 'A', '4', 'l', ']', '7',
       "'", '5', 'B'], dtype='<U1')

In [57]:
epochs=30

In [58]:
model.fit(dataset,epochs=epochs)

Epoch 1/30
  9/351 [..............................] - ETA: 48:12 - loss: 4.8959

KeyboardInterrupt: ignored

## Part Six: Generating Text

In [59]:
from tensorflow.keras.models import load_model

In [64]:
model = create_model(vocab_size,embed_dim,rnn_neurons,batch_size=1)

model.load_weights('shakespeare_gen.h5')

model.build(tf.TensorShape([1,None]))

In [65]:
model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_5 (Embedding)     (1, None, 64)             5376      
                                                                 
 gru_5 (GRU)                 (1, None, 1026)           3361176   
                                                                 
 dense_5 (Dense)             (1, None, 84)             86268     
                                                                 
Total params: 3,452,820
Trainable params: 3,452,820
Non-trainable params: 0
_________________________________________________________________


In [75]:
def generate_text(model,start_seed,gen_size=500,temp=1.0):
  num_generate=gen_size

  input_eval=[char_to_ind[s] for s in start_seed]

  input_eval=tf.expand_dims(input_eval,0)

  text_generated=[]

  temperature=temp

  model.reset_states()

  for i in range(num_generate):
    predictions=model(input_eval)
    predictions=tf.squeeze(predictions,0)
    predictions=predictions/temperature
    predicted_id=tf.random.categorical(predictions,num_samples=1)[-1,0].numpy()
    input_eval=tf.expand_dims([predicted_id],0)
    text_generated.append(ind_to_char[predicted_id])

  return (start_seed+"".join(text_generated))

In [76]:
print(generate_text(model,"JULIET",gen_size=1000))

JULIETES. O, he is worse.
  EUCHEST. There is no thinking, but for otherwise; grant
    again.
  PLADENBEALLES. No, 'Beasol!
  My friend, where is that, that her womb for Rome?
  HOLOFERNES. O, madam, 'tis a bable Protcul
    Say you have scope together arm'd and keep'd;
    You know, my sole will come in to my colour.
  FIRST GENTLEMAN. Yes is not now propp'd on's day to breeding
    the remembrance of it and torture. Katherinate in this;
    For secure thou art wisdom! Lord, how you behinde.
  PETRUCHIO. Friend Louseur come to bed.
  ANTONIO. Either too wildly,
    There thy dwelling men may cam Letrous Stanley;
    Our dull dancing chamberlain, that being done,
    Yet with Sir Toby and lordship were going.
  JULIA. Sir, a gentleman, I'm sure so wisely; I
    Wise a fool's hearing.
  GONZALO. Think'st, sir?
  SIR TOBY. Marry, I think, i' th' matter of his father.
  CALIBAN. I scarce be black is like the honey.
  RODIO. You had already you a bag counterfeitly
    knew her]  too!
    